// Code generated by MockGen. DO NOT EDIT.
// Source: agent_proxy.go
//
// Generated by this command:
//
//	mockgen -source=agent_proxy.go -destination=agent_proxy_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
