// Code generated by MockGen. DO NOT EDIT.
// Source: agent.go
//
// Generated by this command:
//
//	mockgen -source=agent.go -destination=agent_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
