// Code generated by MockGen. DO NOT EDIT.
// Source: data.go
//
// Generated by this command:
//
//	mockgen -source=data.go -destination=data_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
