// Code generated by MockGen. DO NOT EDIT.
// Source: ./client/host.go
//
// Generated by this command:
//
//	mockgen --source=./client/host.go --package client
//
// Package client is a generated GoMock package.
package client
