// Code generated by MockGen. DO NOT EDIT.
// Source: host.go
//
// Generated by this command:
//
//	mockgen -source=host.go -destination=host_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
