// Code generated by MockGen. DO NOT EDIT.
// Source: listener.go
//
// Generated by this command:
//
//	mockgen -source=listener.go -destination=listener_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
