// Code generated by MockGen. DO NOT EDIT.
// Source: packet.go
//
// Generated by this command:
//
//	mockgen -source=packet.go -destination=packet_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
