// Code generated by MockGen. DO NOT EDIT.
// Source: proxy.go
//
// Generated by this command:
//
//	mockgen -source=proxy.go -destination=proxy_mock_test.go -package=client
//
// Package client is a generated GoMock package.
package client
