// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: proto/yampr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{0}
}

func (x *AuthToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type WaitForOfferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  *AuthToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	HostId string     `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *WaitForOfferRequest) Reset() {
	*x = WaitForOfferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitForOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForOfferRequest) ProtoMessage() {}

func (x *WaitForOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForOfferRequest.ProtoReflect.Descriptor instead.
func (*WaitForOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{1}
}

func (x *WaitForOfferRequest) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *WaitForOfferRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

type WaitForOfferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnswererId string `protobuf:"bytes,1,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
	Offer      string `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *WaitForOfferResponse) Reset() {
	*x = WaitForOfferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitForOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForOfferResponse) ProtoMessage() {}

func (x *WaitForOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForOfferResponse.ProtoReflect.Descriptor instead.
func (*WaitForOfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{2}
}

func (x *WaitForOfferResponse) GetAnswererId() string {
	if x != nil {
		return x.AnswererId
	}
	return ""
}

func (x *WaitForOfferResponse) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

type ReplyToRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      *AuthToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OffererId  string     `protobuf:"bytes,2,opt,name=offerer_id,json=offererId,proto3" json:"offerer_id,omitempty"`
	AnswererId string     `protobuf:"bytes,3,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
	Body       string     `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ReplyToRequest) Reset() {
	*x = ReplyToRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyToRequest) ProtoMessage() {}

func (x *ReplyToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyToRequest.ProtoReflect.Descriptor instead.
func (*ReplyToRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyToRequest) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ReplyToRequest) GetOffererId() string {
	if x != nil {
		return x.OffererId
	}
	return ""
}

func (x *ReplyToRequest) GetAnswererId() string {
	if x != nil {
		return x.AnswererId
	}
	return ""
}

func (x *ReplyToRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type AnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *AnswerResponse) Reset() {
	*x = AnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResponse) ProtoMessage() {}

func (x *AnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResponse.ProtoReflect.Descriptor instead.
func (*AnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{4}
}

func (x *AnswerResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type WaitForAnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      *AuthToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AnswererId string     `protobuf:"bytes,2,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
}

func (x *WaitForAnswerRequest) Reset() {
	*x = WaitForAnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitForAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForAnswerRequest) ProtoMessage() {}

func (x *WaitForAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForAnswerRequest.ProtoReflect.Descriptor instead.
func (*WaitForAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{5}
}

func (x *WaitForAnswerRequest) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *WaitForAnswerRequest) GetAnswererId() string {
	if x != nil {
		return x.AnswererId
	}
	return ""
}

type IceCandidate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate string `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{6}
}

func (x *IceCandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type SendIceCandidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendIceCandidateResponse) Reset() {
	*x = SendIceCandidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendIceCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendIceCandidateResponse) ProtoMessage() {}

func (x *SendIceCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendIceCandidateResponse.ProtoReflect.Descriptor instead.
func (*SendIceCandidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{7}
}

type SendOfferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  *AuthToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	HostId string     `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Offer  string     `protobuf:"bytes,3,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *SendOfferRequest) Reset() {
	*x = SendOfferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOfferRequest) ProtoMessage() {}

func (x *SendOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOfferRequest.ProtoReflect.Descriptor instead.
func (*SendOfferRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{8}
}

func (x *SendOfferRequest) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *SendOfferRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *SendOfferRequest) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

type OfferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OffererId  string `protobuf:"bytes,2,opt,name=offerer_id,json=offererId,proto3" json:"offerer_id,omitempty"`
	AnswererId string `protobuf:"bytes,3,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
	Body       string `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *OfferResponse) Reset() {
	*x = OfferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferResponse) ProtoMessage() {}

func (x *OfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferResponse.ProtoReflect.Descriptor instead.
func (*OfferResponse) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{9}
}

func (x *OfferResponse) GetOffererId() string {
	if x != nil {
		return x.OffererId
	}
	return ""
}

func (x *OfferResponse) GetAnswererId() string {
	if x != nil {
		return x.AnswererId
	}
	return ""
}

func (x *OfferResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type WaitForAnswerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *WaitForAnswerResponse) Reset() {
	*x = WaitForAnswerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitForAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForAnswerResponse) ProtoMessage() {}

func (x *WaitForAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForAnswerResponse.ProtoReflect.Descriptor instead.
func (*WaitForAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{10}
}

func (x *WaitForAnswerResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type WaitForICECandidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      *AuthToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AnswererId string     `protobuf:"bytes,2,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
}

func (x *WaitForICECandidateRequest) Reset() {
	*x = WaitForICECandidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitForICECandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForICECandidateRequest) ProtoMessage() {}

func (x *WaitForICECandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForICECandidateRequest.ProtoReflect.Descriptor instead.
func (*WaitForICECandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{11}
}

func (x *WaitForICECandidateRequest) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *WaitForICECandidateRequest) GetAnswererId() string {
	if x != nil {
		return x.AnswererId
	}
	return ""
}

type InitHostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLogin *UserLogin `protobuf:"bytes,1,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
}

func (x *InitHostRequest) Reset() {
	*x = InitHostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitHostRequest) ProtoMessage() {}

func (x *InitHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitHostRequest.ProtoReflect.Descriptor instead.
func (*InitHostRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{12}
}

func (x *InitHostRequest) GetUserLogin() *UserLogin {
	if x != nil {
		return x.UserLogin
	}
	return nil
}

type InitHostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId       string     `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Token        *AuthToken `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ClientSecret *AuthToken `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
}

func (x *InitHostResponse) Reset() {
	*x = InitHostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitHostResponse) ProtoMessage() {}

func (x *InitHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitHostResponse.ProtoReflect.Descriptor instead.
func (*InitHostResponse) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{13}
}

func (x *InitHostResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *InitHostResponse) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *InitHostResponse) GetClientSecret() *AuthToken {
	if x != nil {
		return x.ClientSecret
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{14}
}

type UserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserLogin) Reset() {
	*x = UserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogin) ProtoMessage() {}

func (x *UserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogin.ProtoReflect.Descriptor instead.
func (*UserLogin) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{15}
}

func (x *UserLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AnswerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      *AuthToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	OffererId  string     `protobuf:"bytes,2,opt,name=offerer_id,json=offererId,proto3" json:"offerer_id,omitempty"`
	AnswererId string     `protobuf:"bytes,3,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
	Body       string     `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *AnswerRequest) Reset() {
	*x = AnswerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_yampr_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerRequest) ProtoMessage() {}

func (x *AnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yampr_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerRequest.ProtoReflect.Descriptor instead.
func (*AnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_yampr_proto_rawDescGZIP(), []int{16}
}

func (x *AnswerRequest) GetToken() *AuthToken {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *AnswerRequest) GetOffererId() string {
	if x != nil {
		return x.OffererId
	}
	return ""
}

func (x *AnswerRequest) GetAnswererId() string {
	if x != nil {
		return x.AnswererId
	}
	return ""
}

func (x *AnswerRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_proto_yampr_proto protoreflect.FileDescriptor

var file_proto_yampr_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x61, 0x6d, 0x70, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x50, 0x0a, 0x13, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f,
	0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x14, 0x57, 0x61, 0x69, 0x74,
	0x46, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x28, 0x0a, 0x0e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x59, 0x0a, 0x14, 0x57, 0x61,
	0x69, 0x74, 0x46, 0x6f, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0c, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x63, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x22, 0x63, 0x0a, 0x0d, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x2f, 0x0a, 0x15, 0x57, 0x61, 0x69,
	0x74, 0x46, 0x6f, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x5f, 0x0a, 0x1a, 0x57, 0x61,
	0x69, 0x74, 0x46, 0x6f, 0x72, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x0f, 0x49,
	0x6e, 0x69, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x22, 0x7e, 0x0a, 0x10, 0x49, 0x6e, 0x69,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2f, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x0c, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x43, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x85, 0x01, 0x0a, 0x0d, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32,
	0x84, 0x02, 0x0a, 0x0d, 0x59, 0x41, 0x4d, 0x52, 0x50, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65,
	0x72, 0x12, 0x36, 0x0a, 0x0c, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x12, 0x14, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x53, 0x65, 0x6e,
	0x64, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x10, 0x53,
	0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x0f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x45, 0x0a, 0x13, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72,
	0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x32, 0x86, 0x02, 0x0a, 0x0c, 0x59, 0x41, 0x4d, 0x52, 0x50,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0d, 0x57, 0x61, 0x69,
	0x74, 0x46, 0x6f, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x57, 0x61, 0x69,
	0x74, 0x46, 0x6f, 0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0f, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x63, 0x65, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x54, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x49, 0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x45, 0x0a, 0x13, 0x57, 0x61, 0x69, 0x74,
	0x46, 0x6f, 0x72, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x1b, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x49, 0x43, 0x45, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x49,
	0x63, 0x65, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00, 0x30, 0x01, 0x32,
	0x63, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x32, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x48, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x48, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x0b, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0a, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x0a, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x22, 0x00, 0x32, 0x3a, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x4e, 0x65, 0x77, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x14,
	0x2e, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x61, 0x79, 0x31, 0x34, 0x32, 0x32, 0x2f, 0x79, 0x61, 0x6d, 0x70, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_yampr_proto_rawDescOnce sync.Once
	file_proto_yampr_proto_rawDescData = file_proto_yampr_proto_rawDesc
)

func file_proto_yampr_proto_rawDescGZIP() []byte {
	file_proto_yampr_proto_rawDescOnce.Do(func() {
		file_proto_yampr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_yampr_proto_rawDescData)
	})
	return file_proto_yampr_proto_rawDescData
}

var file_proto_yampr_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_yampr_proto_goTypes = []interface{}{
	(*AuthToken)(nil),                  // 0: AuthToken
	(*WaitForOfferRequest)(nil),        // 1: WaitForOfferRequest
	(*WaitForOfferResponse)(nil),       // 2: WaitForOfferResponse
	(*ReplyToRequest)(nil),             // 3: ReplyToRequest
	(*AnswerResponse)(nil),             // 4: AnswerResponse
	(*WaitForAnswerRequest)(nil),       // 5: WaitForAnswerRequest
	(*IceCandidate)(nil),               // 6: IceCandidate
	(*SendIceCandidateResponse)(nil),   // 7: SendIceCandidateResponse
	(*SendOfferRequest)(nil),           // 8: SendOfferRequest
	(*OfferResponse)(nil),              // 9: OfferResponse
	(*WaitForAnswerResponse)(nil),      // 10: WaitForAnswerResponse
	(*WaitForICECandidateRequest)(nil), // 11: WaitForICECandidateRequest
	(*InitHostRequest)(nil),            // 12: InitHostRequest
	(*InitHostResponse)(nil),           // 13: InitHostResponse
	(*Empty)(nil),                      // 14: Empty
	(*UserLogin)(nil),                  // 15: UserLogin
	(*AnswerRequest)(nil),              // 16: AnswerRequest
}
var file_proto_yampr_proto_depIdxs = []int32{
	0,  // 0: WaitForOfferRequest.token:type_name -> AuthToken
	0,  // 1: ReplyToRequest.token:type_name -> AuthToken
	0,  // 2: WaitForAnswerRequest.token:type_name -> AuthToken
	0,  // 3: SendOfferRequest.token:type_name -> AuthToken
	0,  // 4: WaitForICECandidateRequest.token:type_name -> AuthToken
	15, // 5: InitHostRequest.user_login:type_name -> UserLogin
	0,  // 6: InitHostResponse.token:type_name -> AuthToken
	0,  // 7: InitHostResponse.client_secret:type_name -> AuthToken
	0,  // 8: AnswerRequest.token:type_name -> AuthToken
	1,  // 9: YAMRPAnswerer.WaitForOffer:input_type -> WaitForOfferRequest
	3,  // 10: YAMRPAnswerer.SendAnswer:input_type -> ReplyToRequest
	3,  // 11: YAMRPAnswerer.SendIceCandidate:input_type -> ReplyToRequest
	11, // 12: YAMRPAnswerer.WaitForICECandidate:input_type -> WaitForICECandidateRequest
	8,  // 13: YAMRPOfferer.SendOffer:input_type -> SendOfferRequest
	5,  // 14: YAMRPOfferer.WaitForAnswer:input_type -> WaitForAnswerRequest
	3,  // 15: YAMRPOfferer.SendIceCandidate:input_type -> ReplyToRequest
	11, // 16: YAMRPOfferer.WaitForICECandidate:input_type -> WaitForICECandidateRequest
	12, // 17: Auth.LoginHost:input_type -> InitHostRequest
	15, // 18: Auth.LoginClient:input_type -> UserLogin
	1,  // 19: Host.ListenNewOffer:input_type -> WaitForOfferRequest
	9,  // 20: YAMRPAnswerer.WaitForOffer:output_type -> OfferResponse
	4,  // 21: YAMRPAnswerer.SendAnswer:output_type -> AnswerResponse
	7,  // 22: YAMRPAnswerer.SendIceCandidate:output_type -> SendIceCandidateResponse
	6,  // 23: YAMRPAnswerer.WaitForICECandidate:output_type -> IceCandidate
	9,  // 24: YAMRPOfferer.SendOffer:output_type -> OfferResponse
	4,  // 25: YAMRPOfferer.WaitForAnswer:output_type -> AnswerResponse
	7,  // 26: YAMRPOfferer.SendIceCandidate:output_type -> SendIceCandidateResponse
	6,  // 27: YAMRPOfferer.WaitForICECandidate:output_type -> IceCandidate
	13, // 28: Auth.LoginHost:output_type -> InitHostResponse
	0,  // 29: Auth.LoginClient:output_type -> AuthToken
	14, // 30: Host.ListenNewOffer:output_type -> Empty
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_yampr_proto_init() }
func file_proto_yampr_proto_init() {
	if File_proto_yampr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_yampr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitForOfferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitForOfferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyToRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitForAnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceCandidate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendIceCandidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOfferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitForAnswerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitForICECandidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitHostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitHostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_yampr_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_yampr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_yampr_proto_goTypes,
		DependencyIndexes: file_proto_yampr_proto_depIdxs,
		MessageInfos:      file_proto_yampr_proto_msgTypes,
	}.Build()
	File_proto_yampr_proto = out.File
	file_proto_yampr_proto_rawDesc = nil
	file_proto_yampr_proto_goTypes = nil
	file_proto_yampr_proto_depIdxs = nil
}
